### ISSUE TITLE
distributed 1.21.8 requires msgpack, which is not installed.

### ISSUE THREAD

**Issue by Jvalal** [GoogleCloudPlatform/tensorflow-without-a-phd#10]
I keep getting this error trying to simply install tf.  Why is none of this simple???

<img width="689" alt="screen shot 2018-07-01 at 8 37 47 pm" src="https://user-images.githubusercontent.com/3803053/42144194-b71f466c-7d6e-11e8-85e6-41ee921b8426.png">

**Comment by Jvalal** [comment]
also getting an error trying to install cert. this is supposed to be easy!

![screen shot 2018-07-02 at 11 33 29 am](https://user-images.githubusercontent.com/3803053/42180869-ae50c34c-7ded-11e8-978c-17c2749670cc.png)

**Comment by stickinyourhead** [comment]
+1

**Comment by martin-gorner** [comment]
For tensorflow and python installation issues, I will kindly direct you to StackOverflow.

**Comment by Jvalal** [comment]
your tutorials should assume a scratch install. You want this to be accessible to more people, right? So providing detailed instructions that don't skip over things would help in this vain. thanks

**Comment by snjjay** [comment]
Because of the way anaconda is installed, the error "distribution 1.21.8 requires msgpack, which is not installed" may occur; the answer is to install msgpack as administrator. https://kodlogs.net/196/distributed-1-21-8-requires-msgpack-which-is-not-installed-fixed
