### ISSUE TITLE
403: Forbidden downloading mnist_data

### ISSUE THREAD

**Issue by diramazioni** [GoogleCloudPlatform/tensorflow-without-a-phd#8]
Hello, 
I've just cloned the repo and trying out the first mnist_1.0_softmax example that attempts to download from https://storage.googleapis.com/cvdf-datasets/mnist/ currently not accessible...
other sources?

**Comment by martin-gorner** [comment]
I am looking into what happened here. In the meantime, you can find the data here: http://yann.lecun.com/exdb/mnist/
Download the files, unzip them and put them in a directory called "data" and the script will not attempt to download them from the faulty URL.

**Comment by diramazioni** [comment]
wow it works! Very well done example and tutorial. tensorflowvisu is also quite useful as a tool to reuse in other projects, I'm digging into the source :)
What's the best way to ask questions about the code? (if possible at all)

**Comment by martin-gorner** [comment]
For visualisations I recommend Tensorboard. I did it differently in this sample only because I wanted the visualisations to animate as training progressed but that's just for show.

**Comment by martin-gorner** [comment]
For questions: Twitter (DM or not depending on public interest)

**Comment by martin-gorner** [comment]
The links seem to be working again:
https://storage.googleapis.com/cvdf-datasets/mnist/t10k-labels-idx1-ubyte.gz
https://storage.googleapis.com/cvdf-datasets/mnist/t10k-images-idx3-ubyte.gz
https://storage.googleapis.com/cvdf-datasets/mnist/train-labels-idx1-ubyte.gz
https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz
 Thank you for reporting this.
